### ISSUE TITLE
Supabase api url vs hosting locally

### ISSUE THREAD

**Issue by ghost** [iswilljr/xlug#22]
Is there an easy way to host the database directly on Supabase using an api url vs locally hosting it through a docker container?

**Comment by tuckerjr** [comment]
Read up on the supabase docs more and found a solution my bad

**Comment by tuckerjr** [comment]
Any chance you'd willing to remove this issue I'm going to make a pr later with steps with deploying to supabase.com rather then just a localhost docker setup.

**Comment by iswilljr** [comment]
If you want to use a Supabase project instead of running a local Supabase instance, you can copy the supabase api url and the anon public key and then paste them into the `.env` file.

I will setup a guide for this.

**Comment by iswilljr** [comment]
added a guide on how to link to a supabase project in #23
